# Generated by Django 3.2.6 on 2021-08-14 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.TextField(default='Siriba campus - Nyawita', max_length=255)),
                ('physical_location', models.CharField(default='Maseno Student Center - Left Side Pocket', max_length=255)),
                ('email', models.EmailField(default='asiafric@gmail.com', max_length=100)),
                ('tel', models.CharField(default='254711349412', max_length=12)),
                ('facebook', models.URLField(default='facebook.com')),
                ('twitter', models.URLField(default='twitter.com')),
                ('youtube', models.URLField(default='youtube.com')),
                ('instagram', models.URLField(default='instagram.com')),
                ('tiktok', models.URLField(default='tiktok.com')),
                ('linkedin', models.URLField(default='linkedin.com')),
                ('other', models.URLField(blank=True, default='enter any aditional social media url', null=True)),
                ('rights_year', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Organisation contacts and location',
            },
        ),
        migrations.CreateModel(
            name='Customblogname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogname', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Blog name',
            },
        ),
        migrations.CreateModel(
            name='FQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='Question 1', max_length=255)),
                ('answer', models.TextField(default='Answer for question 1', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'FQA',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/images/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Howitworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=100)),
                ('content', models.TextField(default='Content', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'How it works',
            },
        ),
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Stuff & Contacts Ranks',
            },
        ),
        migrations.CreateModel(
            name='Site_Policies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.TextField(default='Add site terms and conditions here', max_length=255)),
                ('privacy_policy', models.TextField(default='Add your privacy policy here', max_length=255)),
                ('cookies_policy', models.TextField(default='Add your coockies policy here', max_length=255)),
                ('adds_info', models.TextField(default='Add info', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Site Policies',
            },
        ),
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_party_name', models.CharField(default='TDBSoft', max_length=100)),
                ('third_party_site', models.URLField(default='tdbsoft.pythonanywhere.com', max_length=255)),
                ('third_party_phone', models.TextField(default='+254743793901', max_length=15)),
                ('third_party_email', models.EmailField(default='infotdbsoft@gmail.com', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Third Party',
            },
        ),
        migrations.CreateModel(
            name='UpdateLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='logo.png', upload_to='logo/')),
            ],
            options={
                'verbose_name_plural': 'Update Logo',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('dateadded', models.DateTimeField(auto_now_add=True)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteconfig.ranks')),
            ],
            options={
                'verbose_name_plural': 'Add Contacts',
            },
        ),
    ]
