# Generated by Django 3.2.6 on 2021-08-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranks',
            options={'verbose_name_plural': 'Stuff & Contacts Ranks'},
        ),
    ]
