# Generated by Django 3.2.6 on 2021-08-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_contacts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='other',
            field=models.URLField(blank=True, default='example.com', null=True),
        ),
    ]
