# Generated by Django 3.2.6 on 2021-08-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_alter_ranks_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name_plural': 'Add Contacts'},
        ),
        migrations.AlterField(
            model_name='about',
            name='other',
            field=models.URLField(blank=True, default='enter any aditional social media url', null=True),
        ),
    ]
