# Generated by Django 3.2.6 on 2021-08-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0003_auto_20210813_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='physical_location',
            field=models.CharField(default='Maseno Student Center - Left Side Pocket', max_length=255),
        ),
    ]
