# Generated by Django 3.2.6 on 2021-08-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0004_alter_about_physical_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='linkedin',
            field=models.URLField(default='linkedin.com'),
        ),
        migrations.AddField(
            model_name='about',
            name='tiktok',
            field=models.URLField(default='tiktok.com'),
        ),
        migrations.AlterField(
            model_name='about',
            name='facebook',
            field=models.URLField(default='facebook.com'),
        ),
        migrations.AlterField(
            model_name='about',
            name='instagram',
            field=models.URLField(default='instagram.com'),
        ),
        migrations.AlterField(
            model_name='about',
            name='twitter',
            field=models.URLField(default='twitter.com'),
        ),
        migrations.AlterField(
            model_name='about',
            name='youtube',
            field=models.URLField(default='youtube.com'),
        ),
    ]
