# Generated by Django 3.2.6 on 2021-08-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0005_auto_20210813_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='FQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='Question 1', max_length=255)),
                ('answer', models.TextField(default='Answer for question 1', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Howitworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=100)),
                ('content', models.TextField(default='Content', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'How it works',
            },
        ),
        migrations.CreateModel(
            name='Site_Policies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.TextField(default='Add site terms and conditions here', max_length=255)),
                ('privacy_policy', models.TextField(default='Add your privacy policy here', max_length=255)),
                ('cookies_policy', models.TextField(default='Add your coockies policy here', max_length=255)),
                ('adds_info', models.TextField(default='Add info', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Site Policies',
            },
        ),
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_party_name', models.CharField(default='TDBSoft', max_length=100)),
                ('third_party_site', models.URLField(default='tdbsoft.pythonanywhere.com', max_length=255)),
                ('third_party_phone', models.TextField(default='+254743793901', max_length=15)),
                ('third_party_email', models.EmailField(default='infotdbsoft@gmail.com', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Third Party',
            },
        ),
    ]
